from scrapy.item import Item, Field

class HealthiItem(Item):
	response_url = Field()
	establishment_name = Field()
	address = Field()
	city_state_zip = Field()
	telephone = Field()
	date_of_inspection = Field()
	license_holder = Field()
	establishment_type = Field()
	risk_category = Field()
	type_of_inspection = Field()
	license_customer_number = Field()
	time_in = Field()
	time_out = Field()
	email_address = Field()
	name_of_licensed_trash_or_solid_waste_contractor = Field()
	name_of_licensed_liquid_grease_collections_transport_contractor = Field()
	name_of_licensed_pest_exterminator_contractor = Field()
	cfpm_number = Field()
	cfpm_expiration_date = Field()
	certified_food_protection_manager = Field()
	license_period_start = Field()
	license_period_end = Field()
	noncritical_violations = Field()
	critical_violations = Field()
	compliance_line_items = Field()
	observations = Field()